import type { Metadata } from "next";

import Header from "@/components/Header";
import { poppins } from "@/lib/utils";
import "./globals.css";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <head>
        <script
          defer
          src={`https://maps.googleapis.com/maps/api/js?key=${process.env.MAPS_API_KEY}`}
        ></script>
      </head>
      <body className={`${poppins.className} antialiased relative h-full`}>
        <main className="relative flex flex-col min-h-screen">
          <Header />
          <div className="flex-grow flex-1">{children}</div>
          <Toaster />
          <Footer />
        </main>
      </body>
    </html>
  );
}
